### PR TITLE
[PRD-646] fix negative progress in provision

### PR DESCRIPTION
**Pull request by AlexanderPavlenko**
validates progress reports not only for `deploy` action
tested manually by deploying HA cluster

### CODE REVIEW

**Comment by adanin** [comment]
+1
Maybe some unit tests for it?

**Comment by mihgen** [comment]
What does it fix? For deploy method it actually the same code; node_type and remove_node don't even need to use proxy reporter, do they?

**Comment by adanin** [comment]
I agree with Mike. Proxy for deploy call only.
And what about unit test for this case?

**Comment by AlexanderPavlenko** [comment]
> What does it fix?

It prevents sending lower progress than it was before. I was unable to debug and fix ParseProvisionLogs, which falls into negative progress numbers for HA deployments, so for now it just waits on the same % in these situations.

> Proxy for deploy call only.

Well, as you can see not only the deploy progress calculation is buggy.

**Pull request closed without merging**
